#----------------------
#\LiteCustomStopServer/
#----------------------
#config.yml
#插件作者:主世界
#本插件已免费发布并在Github上开源

#设置输入/lcss stop后多少秒关服
seconds: 60
#设置进入关服倒计时后分别在剩余多少秒时再次发送关服公告
countdown:
  - 30
  - 10
  - 5
#设置定时关服时间;若不想启用本功能请将第一个值设为none
#"是否删除"表示的是该定时关服是否为一次性的,若是则填写1,不是填写0
#格式:'HH-mm,是否删除'
auto-stop-time:
  - '00-00,0'
  - '06-00,0'
  - '20-00,1'
#设置是否在关服公告发出同时显示Title文字
title-true-or-false: 'true'